### ISSUE TITLE
I can't implement this im my kotlin project to change drawable color

### ISSUE THREAD

**Issue by ghost** [OlegTarashkevich/ObservableBackground#1]
Hi,

I this its wrong:
<FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@{viewModel.background}">

The correct is:
      <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@{background.mColorValue}">

What about de <data> tag?  I will need or not?

**Comment by prilaga** [comment]
Hi @neuberfran,
I'm not sure that I understand you. Could you please rephrase. 

This class using only with data binding. You need to create your own ViewModel class, 
add ` val background = ObservableBackground()`,
setup data binding in xml and set `android:background="@{viewModel.background}"`

**Comment by ghost** [comment]
what I put in mainactivity?
